### PR TITLE
Fix tests 

### PR DESCRIPTION
**Pull request by celyes**
fixed testing database issues. @kossa

### CODE REVIEW

**Comment by kossa** [comment]
@celyes why you removed "Database\\Migrations\\": "database/migrations/", from composer.json

**Comment by celyes** [comment]
@kossa that was a mistake. please check now.

**Comment by kossa** [comment]
@celyes Thank still only one database/migrations/create_cities_table.php.stub you removed the namespace

**Comment by celyes** [comment]
Sure. I'm using phpstorm so it must've been an auto-refactoring thing.

**Comment by celyes** [comment]
@kossa Check now.

**Pull request merged**
